### ISSUE TITLE
Support WA-Multi?

### ISSUE THREAD

**Issue by Diden05** [dimaskiddo/go-whatsapp-rest#53]
Hi, do you plan to support this library https://github.com/tulir/whatsmeow?

**Comment by dimaskiddo** [comment]
Hi, multi-session is already supported long time ago in this repository, the differences is, it is manage by saving the session file seperatedly when you putting a JID / MSISDN on Basic Auth, but in that library tulir has made improvement by saving it into a database like sqlite and of course better handling i think.

So for multi WA session this already supported as it's saved your session seperatedly when creating an auth token, it's why auth username must a JID / MSISDN

But this doesn't mean that there are no possibilities to use repository from tulir, since tulir it self a contributor fo go-whatsapp, may be in my free time i'll try to implement or migrated to use it

Thanks 😄

**Comment by Diden05** [comment]
The tulir library for other purposes, it uses whatsapp beta (https://faq.whatsapp.com/general/download-and-installation/about-multi-device-beta/?lang=en) which allows you not to keep your phone connected all the time. This is its advantage over whatsapp-go
She is multi-devices, not multi-sessions

**Comment by dimaskiddo** [comment]
I see, that's why it's need SQLite, to save all data in local. If there are spesific needs that you can give me an example of case may be i can try to implement it, but in different repository may be.

Thanks btw for your information

**Comment by ibnux** [comment]
i think this Multi Device Beta has been release, in iphone its been default. Maybe in some next month all Whatsapp Web Client will be Multi Device Feature. and all Unofficial Client need to migrate

**Comment by dimaskiddo** [comment]
Agreed Pak @ibnux IOS and Android already Forced to Use WA Multi-Devices event the WhatsApp Desktop already close QR for Old Connection Type and Force it to use The Multi Device One.

There are also alot of advantages when we use Multi Device, but i need to fully recode it, because the library is not backward compatible, it's really new library develop by tulir as one of contributor on Rhymen.

Thank's for all attention to this repository, i hope i can back to active development to create a new code and repository as my follow up to keep up-to-date with WhatsApp.

**Comment by dimaskiddo** [comment]
Currently still in development for multi-device support, check it out
https://github.com/dimaskiddo/go-whatsapp-multidevice-rest

Thanks 😄 ❤️
