### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by iileandro** [dimaskiddo/go-whatsapp-rest#7]
New issue on the base lib:

https://github.com/Rhymen/go-whatsapp/issues/170

New login not working.

**Comment by iileandro** [comment]
I saw you've fixed the whatsapp version. I'm a little confused tryingo to maitain the fork you made from Rhymen/go-whatsapp. Could you tell me why did you fork it. It's just to help me to understand the fixes.

**Comment by dimaskiddo** [comment]
Make sure to re run make init, i already update the whatsapp web version

I belive the issue is the whatsapp web version, since last issue you debug also returning update command from the whatsapp server

So i try it and got same issue where login doesn't return any qrCode, updating the whatsapp web version in init command does resolved the issue

The concern using of my own fork is to keep track my own pick from the main repo and i do some modification in my own flavour

It's your choice if you want to use the main repo, it should not have any problem with this example as long as there are no function changes due to refactor

**Comment by dimaskiddo** [comment]
By this Commit ID e66c14d4f67b4a5933b7cab46cb7f56d1edf9106  and updating WhatsApp Web version to 0.3.3328 in Login/Restore session request should fix this issue. Thank's
